function sub_400870 {
    rsp = rsp - 0x8;
    rax = __ctype_b_loc(arg0);
    rdx = *(int8_t *)0x6042c0 & 0xff;
    rax = *rax;
    if ((*(int8_t *)(rax + rdx * 0x2 + 0x1) & 0x2) == 0x0) {
            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c0 & 0xff) * 0x2) & 0x8) != 0x0) {
                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c1 & 0xff) * 0x2 + 0x1) & 0x8) == 0x0) {
                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c1 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c2 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c2 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c3 & 0xff) * 0x2) & 0x8) == 0x0) {
                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c3 & 0xff) * 0x2 + 0x1) & 0x4) == 0x0) {
                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c4 & 0xff) * 0x2 + 0x1) & 0x2) == 0x0) {
                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c4 & 0xff) * 0x2 + 0x1) & 0x8) != 0x0) {
                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c5 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c5 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c6 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c6 & 0xff) * 0x2 + 0x1) & 0x8) == 0x0) {
                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c7 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c7 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c8 & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c8 & 0xff) * 0x2 + 0x1) & 0x2) == 0x0) {
                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042c9 & 0xff) * 0x2 + 0x1) & 0x1) != 0x0) {
                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042c9 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042ca & 0xff) * 0x2 + 0x1) & 0x2) != 0x0) {
                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042ca & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042cb & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042cb & 0xff) * 0x2 + 0x1) & 0x2) != 0x0) {
                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042cc & 0xff) * 0x2 + 0x1) & 0x8) == 0x0) {
                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042cc & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042cd & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042cd & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042ce & 0xff) * 0x2 + 0x1) & 0x2) == 0x0) {
                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042ce & 0xff) * 0x2 + 0x1) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042cf & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042cf & 0xff) * 0x2 + 0x1) & 0x8) == 0x0) {
                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d0 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d0 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d1 & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d1 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d2 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d2 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d3 & 0xff) * 0x2 + 0x1) & 0x2) != 0x0) {
                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d3 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d4 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d4 & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d5 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d5 & 0xff) * 0x2 + 0x1) & 0x2) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d6 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d6 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d7 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d7 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d8 & 0xff) * 0x2 + 0x1) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d8 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042d9 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042d9 & 0xff) * 0x2 + 0x1) & 0x2) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042da & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042da & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042db & 0xff) * 0x2 + 0x1) & 0x8) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042db & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042dc & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042dc & 0xff) * 0x2 + 0x1) & 0x2) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042dd & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042dd & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042de & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042de & 0xff) * 0x2 + 0x1) & 0x2) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042df & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042df & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e0 & 0xff) * 0x2 + 0x1) & 0x2) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e0 & 0xff) * 0x2 + 0x1) & 0x1) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e1 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e1 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e2 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e2 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e3 & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e3 & 0xff) * 0x2 + 0x1) & 0x2) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e4 & 0xff) * 0x2 + 0x1) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e4 & 0xff) * 0x2 + 0x1) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e5 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e5 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e6 & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e6 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e7 & 0xff) * 0x2 + 0x1) & 0x2) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e7 & 0xff) * 0x2 + 0x1) & 0x8) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e8 & 0xff) * 0x2 + 0x1) & 0x2) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e8 & 0xff) * 0x2 + 0x1) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042e9 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042e9 & 0xff) * 0x2 + 0x1) & 0x2) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042ea & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042ea & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042eb & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042eb & 0xff) * 0x2 + 0x1) & 0x8) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042ec & 0xff) * 0x2 + 0x1) & 0x8) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042ec & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042ed & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042ed & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042ee & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042ee & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042ef & 0xff) * 0x2 + 0x1) & 0x4) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042ef & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042f0 & 0xff) * 0x2) & 0x8) != 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042f0 & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042f1 & 0xff) * 0x2) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042f1 & 0xff) * 0x2 + 0x1) & 0x1) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if ((*(int8_t *)(rax + (*(int8_t *)0x6042f2 & 0xff) * 0x2 + 0x1) & 0x4) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if ((*(int8_t *)(rax + (*(int8_t *)0x6042f2 & 0xff) * 0x2) & 0x8) == 0x0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rax = 0x1;